// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/it-happened/eventest/internal/runtime (interfaces: Clock)
//
// Generated by this command:
//
//	mockgen -package mockruntime -destination internal/mocks/runtime/clock.go github.com/thomas-marquis/it-happened/eventest/internal/runtime Clock
//

// Package mockruntime is a generated GoMock package.
package mockruntime

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Elapsed mocks base method.
func (m *MockClock) Elapsed() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Elapsed")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Elapsed indicates an expected call of Elapsed.
func (mr *MockClockMockRecorder) Elapsed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Elapsed", reflect.TypeOf((*MockClock)(nil).Elapsed))
}

// Forward mocks base method.
func (m *MockClock) Forward(duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Forward", duration)
}

// Forward indicates an expected call of Forward.
func (mr *MockClockMockRecorder) Forward(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forward", reflect.TypeOf((*MockClock)(nil).Forward), duration)
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// Schedule mocks base method.
func (m *MockClock) Schedule(delay time.Duration, f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Schedule", delay, f)
}

// Schedule indicates an expected call of Schedule.
func (mr *MockClockMockRecorder) Schedule(delay, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockClock)(nil).Schedule), delay, f)
}

// Start mocks base method.
func (m *MockClock) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockClockMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockClock)(nil).Start))
}

// StartTime mocks base method.
func (m *MockClock) StartTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartTime indicates an expected call of StartTime.
func (mr *MockClockMockRecorder) StartTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTime", reflect.TypeOf((*MockClock)(nil).StartTime))
}

// Started mocks base method.
func (m *MockClock) Started() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Started")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Started indicates an expected call of Started.
func (mr *MockClockMockRecorder) Started() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Started", reflect.TypeOf((*MockClock)(nil).Started))
}

// Stop mocks base method.
func (m *MockClock) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockClockMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockClock)(nil).Stop))
}
