// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/it-happened/event (interfaces: Notifier)
//
// Generated by this command:
//
//	mockgen -package mocks_events -destination internal/mocks/events/notifier.go github.com/thomas-marquis/it-happened/event Notifier
//

// Package mocks_events is a generated GoMock package.
package mocks_events

import (
	reflect "reflect"

	event "github.com/thomas-marquis/it-happened/event"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyPublished mocks base method.
func (m *MockNotifier) NotifyPublished(arg0 event.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyPublished", arg0)
}

// NotifyPublished indicates an expected call of NotifyPublished.
func (mr *MockNotifierMockRecorder) NotifyPublished(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPublished", reflect.TypeOf((*MockNotifier)(nil).NotifyPublished), arg0)
}

// NotifySubscribed mocks base method.
func (m *MockNotifier) NotifySubscribed(subscriber *event.Subscriber) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifySubscribed", subscriber)
}

// NotifySubscribed indicates an expected call of NotifySubscribed.
func (mr *MockNotifierMockRecorder) NotifySubscribed(subscriber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifySubscribed", reflect.TypeOf((*MockNotifier)(nil).NotifySubscribed), subscriber)
}

// NotifyUnsubscribed mocks base method.
func (m *MockNotifier) NotifyUnsubscribed(subscriber *event.Subscriber) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyUnsubscribed", subscriber)
}

// NotifyUnsubscribed indicates an expected call of NotifyUnsubscribed.
func (mr *MockNotifierMockRecorder) NotifyUnsubscribed(subscriber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUnsubscribed", reflect.TypeOf((*MockNotifier)(nil).NotifyUnsubscribed), subscriber)
}
